language: python
python:
- '3.5'
install: pip install -r requirements.txt
script: py.test
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: mike.e.charles@gmail.com
  organization: mikecharles
  space: development
  password:
    secure: mFW5uxwQHKqCEOPzXDSiQRkJNCv8TszqrCkzUfnyxSjiemasx6mxUiIJkg+FErOGlE+FeAoJVsM7141kWn9zFz275s82WcW3CIxO5Lz9Q8nH8+Qct1xzvIcAOYpGP1nZR3XS0BUWiDk68QEYURu2bHix+NxOToE96uqCL7GY+jHv1/1pK3496W30aRp7dVCokIHFC+HHOWRdlR10xbqHDUf2c8UIz4K6ZcrQ+DyJ9a+iOCgJ7RJgvjQn/cwTEtcpbz9MeDMHSvChOWDSAKG3+Nt6kPT9WEK3irJ17/CY7D84+u6LabucaFVuAHfJdKt4AWXOqiMekoABW35zsH1i5KKOFIWUDthF2v+MvODfL9XWZaFplMqwdkxfaeKmwyGKtY8HQc4pXRw6/lFgKZsCTfRrqwzZJqQV2W+dYBWt8oeWFO1GwSM6YyIO9l0jyypBsdLsr2tYUPXwN3JNUfDBuxeXFkdZ3lEL+eQd7ra9N9gj0KWEjVTmAYgu6142ulxxWLYkyapprymY26xrr9ceZjaMiojoGlGNqf6OsMJNip55s50+7ho0FzEwysyjshYFwy5+PwqjOYmDK7ytrn1ULrxe6NgA2l0HEbfpEmRcbHWQjnfW5nFkWgUTeQCw8yrZt9e+02eaUoAxmG3ognFfKjJU60lIUcSegC8fotWSNrc=
