language: python
python:
- '3.5'
install: pip install -r requirements.txt
script: py.test
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: mike.e.charles@gmail.com
  organization: mikecharles
  space: development
  password:
    secure: q03G/legaOUtkNwiNHpcnUa97E2fzgVwzE3nGePl9hK/qlrFE1aNeBr6ZsoqEkdlnPKWYJXsRQYXg1krUjzFRv7QMdw8gTqFcXiFKNk+81HIfoRJ94pQ4KClcC0nJzor4fL0QJON630Y3bcUCjeYFe6uOaNXqHYsod0wt8et54b5x6C9ERq65P5EZSIoUxWvNjBoctaTzQtQ5MxbAyINwKaoZQPLLfIj9Z5ZvwuxWHLIrpyFeZ3jx8v38hTL4fjl/d4jY34lzUEN+YaeXCjyKDRlFNQZrDWwiyx9ocerQHgXA6tZrOyqBc37S16sJqP23T0HZYT1K1vMU+oqK2R2nMtgG5o3NpmWHtcER2UHluKQMgaHv6VnaoKQ/zCdtPJLyf4GA0hcDDCcHmke5zXZp280v1ltOJg4G9SBVS4hUNUS57m/lG0EwqbgdLUkoLTZh7kYjer2LoNmXTGHYQfooBuN73H4I1ekq9xy1H7stefwyYxaYi5Kbw/TTtjrdOfIfgNN+UANQNg6ksNQQO4oaYRCD4vISnga28rb3sWNgqEQKk0hm3Uq4OlyiFCJ8InPPVi6/igJgJ0Yj49Y1bpZ4JxodieKIQxO3RipTUkTGKlW43VkroF9NDJe7eXFlWy494djFJZyJK+Qhe5uXmLfimC8/Fp2OxQpLEaNq7qsm5A=
