# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python

python:
  - "3.5"

install: pip install -r requirements.txt

script: py.test
