language: python
python:
- '3.5'
install: pip install -r requirements.txt
script: py.test
deploy:
  edge: true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: mike.e.charles@gmail.com
  organization: mikecharles
  space: development
  password:
    secure: Ga4SjIZtR5FVe2qHS3kwsT2I+CxL8RFLLm004acvgBpDunOB9s/V0Yr938CYmIOaYmVpaXM2bf8rdBwya7l5K42J2sXo3V4dLZs9BnByJdWE2d/6/0fvc2rI2OjlO3VyC2xoWYwzqdRxZDEWLGdWoIH/P9ifs3+oZewz5Dc038D8dUlmAiTpwSZI+uYUXWLlmqAosLP+ZdfPHYcDhzWhNJ9yFcHx6Hl39a0j+VqAgzkWYaiIgYUhyZyzoAMG0RCyoNS19Or9p2RXqhEHQTlvogGLIXzVeArcciVae6zWSsmM9UytRspVSDsLj2CtXiXjfWWAywrQeuD0nOdzGa10Wfpu6ZANm4zhMrlLamelqIdricULASmWJkogu798crrd2W65hjP4L4napx+NLWfniGVnrM9gSpBOrAdKJlX1hDK1k5kW9xZ6agfzNp4ybfyVNWCHySKwbpEN0rzwhVlS1QRzX2IID9y8KwD9FT5qYhpzMsoMz8/j15Iu9iiGgpItx4XoJKaYkGbvsYN1fLK8P3E/QgK7cuCx9x/DKSkoiMGMozej2MLrPoBsO30HVMb4yuArui1k5lEiaTAeDZ/An/dJ9lwIQiTDjVqHvhEV52r22n8vZqCKiyLW+v4GuYrnyA3ZhYPt/ib5MpVnflXc3ZuxNVtt3wK4Xjvthu6qwO8=
